# Generated by Django 6.0.1 on 2026-01-16 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0003_add_initial_cities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Ex: Kasbah de Tanger, Grottes d'Hercule", max_length=200, verbose_name='Nom du lieu')),
                ('description', models.TextField(help_text='Décrivez le lieu en 2-3 phrases', verbose_name='Description')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Adresse')),
                ('entry_price', models.DecimalField(blank=True, decimal_places=2, help_text='Prix en dirhams marocains', max_digits=6, null=True, verbose_name="Prix d'entrée (DH)")),
                ('opening_hours', models.CharField(blank=True, help_text='Ex: 9h00 - 18h00, Fermé le lundi', max_length=100, null=True, verbose_name="Horaires d'ouverture")),
                ('best_time_to_visit', models.CharField(blank=True, help_text="Ex: Printemps, Été, Toute l'année", max_length=100, null=True, verbose_name='Meilleure période')),
                ('category', models.CharField(choices=[('monument', 'Monument historique'), ('musee', 'Musée'), ('nature', 'Site naturel'), ('plage', 'Plage'), ('souk', 'Marché traditionnel (Souk)'), ('jardin', 'Jardin/parc'), ('mosquee', 'Lieu religieux'), ('kasbah', 'Forteresse/Kasbah')], default='monument', max_length=50, verbose_name='Catégorie')),
                ('latitude', models.FloatField(blank=True, help_text='Coordonnée GPS pour la carte', null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, help_text='Coordonnée GPS pour la carte', null=True, verbose_name='Longitude')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='places/main/', verbose_name='Image principale')),
                ('additional_images', models.TextField(blank=True, help_text='URLs séparées par des virgules', null=True, verbose_name="URLs d'images supplémentaires")),
                ('is_featured', models.BooleanField(default=False, help_text='Afficher en priorité sur le site', verbose_name='Mis en avant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('city', models.ForeignKey(help_text='Ville marocaine où se trouve le lieu', on_delete=django.db.models.deletion.CASCADE, related_name='place_list', to='cities.city', verbose_name='Ville')),
            ],
            options={
                'verbose_name': 'Lieu touristique',
                'verbose_name_plural': 'Lieux touristiques',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='places/gallery/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Légende')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload")),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_images', to='places.place', verbose_name='Lieu')),
            ],
            options={
                'verbose_name': 'Image de lieu',
                'verbose_name_plural': 'Images de lieu',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=100, verbose_name='Nom du visiteur')),
                ('rating', models.IntegerField(choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], default=3, verbose_name='Note')),
                ('comment', models.TextField(max_length=500, verbose_name='Commentaire')),
                ('visit_date', models.DateField(verbose_name='Date de visite')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de publication')),
                ('is_approved', models.BooleanField(default=False, help_text="L'avis doit être approuvé avant publication", verbose_name='Approuvé')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_reviews', to='places.place', verbose_name='Lieu')),
            ],
            options={
                'verbose_name': 'Avis visiteur',
                'verbose_name_plural': 'Avis visiteurs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['name'], name='places_plac_name_39c762_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['city', 'category'], name='places_plac_city_id_8d500c_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['is_featured'], name='places_plac_is_feat_c17c5f_idx'),
        ),
    ]
