# Generated by Django 6.0.1 on 2026-01-24 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0004_alter_touristplace_city'),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeimage',
            name='place',
        ),
        migrations.RemoveField(
            model_name='visitorreview',
            name='place',
        ),
        migrations.RemoveIndex(
            model_name='place',
            name='places_plac_name_39c762_idx',
        ),
        migrations.RemoveIndex(
            model_name='place',
            name='places_plac_city_id_8d500c_idx',
        ),
        migrations.RemoveIndex(
            model_name='place',
            name='places_plac_is_feat_c17c5f_idx',
        ),
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='places/', verbose_name='Image du lieu'),
        ),
        migrations.AlterField(
            model_name='place',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='cities.city', verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='place',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.FloatField(default=31.6295, help_text='Ex: 31.6295', verbose_name='Latitude'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.FloatField(default=-7.9811, help_text='Ex: -7.9811', verbose_name='Longitude'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nom du lieu'),
        ),
        migrations.AlterField(
            model_name='place',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='PlaceImage',
        ),
        migrations.DeleteModel(
            name='VisitorReview',
        ),
        migrations.RemoveField(
            model_name='place',
            name='additional_images',
        ),
        migrations.RemoveField(
            model_name='place',
            name='address',
        ),
        migrations.RemoveField(
            model_name='place',
            name='best_time_to_visit',
        ),
        migrations.RemoveField(
            model_name='place',
            name='category',
        ),
        migrations.RemoveField(
            model_name='place',
            name='entry_price',
        ),
        migrations.RemoveField(
            model_name='place',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='place',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='place',
            name='opening_hours',
        ),
    ]
