# Generated by Django 4.2.7 on 2026-01-30 18:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0004_alter_touristplace_city'),
        ('places', '0003_alter_place_options_remove_place_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['name'], 'verbose_name': 'Lieu touristique', 'verbose_name_plural': 'Lieux touristiques'},
        ),
        migrations.RemoveField(
            model_name='place',
            name='address',
        ),
        migrations.RemoveField(
            model_name='place',
            name='entrance_fee',
        ),
        migrations.RemoveField(
            model_name='place',
            name='is_free',
        ),
        migrations.RemoveField(
            model_name='place',
            name='place_type',
        ),
        migrations.AddField(
            model_name='place',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='cities.city', verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='places/', verbose_name='Image du lieu'),
        ),
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.FloatField(help_text='Ex: 31.6295', verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.FloatField(help_text='Ex: -7.9811', verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nom du lieu'),
        ),
        migrations.DeleteModel(
            name='Stadium',
        ),
    ]
