# Generated by Django 5.2.10 on 2026-01-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(default="default.jpg", upload_to="profile_pics/"),
        ),
    ]
