# Generated by Django 5.2.10 on 2026-01-28 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0004_alter_touristplace_city'),
        ('hotels', '0005_add_hotels_data'),
        ('places', '0002_remove_placeimage_place_remove_visitorreview_place_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration_days', models.IntegerField()),
                ('difficulty', models.CharField(choices=[('facile', 'Facile'), ('moyen', 'Moyen'), ('difficile', 'Difficile')], max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='itineraries/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel_name', models.CharField(max_length=200)),
                ('hotel_rating', models.IntegerField()),
                ('hotel_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hotel_address', models.CharField(max_length=300)),
                ('stadium_name', models.CharField(max_length=200)),
                ('stadium_address', models.CharField(max_length=300)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=6)),
                ('best_season', models.CharField(default="Toute l'année", max_length=100)),
                ('required_equipment', models.TextField()),
                ('contact_info', models.CharField(max_length=200)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='Anonyme', max_length=100)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='routes.itinerary')),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities.city')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.hotel')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='routes.customitinerary')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.place')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('from_location', models.CharField(max_length=200)),
                ('to_location', models.CharField(max_length=200)),
                ('stadium_name', models.CharField(max_length=200)),
                ('stadium_address', models.CharField(max_length=300)),
                ('distance_km', models.FloatField()),
                ('estimated_time_min', models.IntegerField()),
                ('transport_mode', models.CharField(default='Taxi', max_length=50)),
                ('price_estimate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('latitude_start', models.FloatField(default=0.0)),
                ('longitude_start', models.FloatField(default=0.0)),
                ('latitude_end', models.FloatField()),
                ('longitude_end', models.FloatField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='hotels.hotel')),
            ],
        ),
    ]
