# Generated by Django 5.2.10 on 2026-01-30 19:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0004_alter_touristplace_city'),
        ('hotels', '0008_remove_hotel_address_alter_hotel_price_and_more'),
        ('places', '0004_alter_place_options_remove_place_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=200, verbose_name='Hôtel de départ')),
                ('stadium_name', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True)),
                ('duration_days', models.PositiveIntegerField(default=1, help_text='Durée en jours')),
                ('difficulty', models.CharField(choices=[('easy', 'Facile'), ('medium', 'Moyen'), ('hard', 'Difficile')], default='medium', max_length=10)),
                ('google_maps_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cities', models.ManyToManyField(blank=True, related_name='itineraries_list', to='cities.city')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('stop_type', models.CharField(choices=[('place', 'Lieu touristique'), ('hotel', 'Hôtel'), ('city', 'Ville'), ('other', 'Autre')], default='place', max_length=10)),
                ('custom_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom personnalisé')),
                ('description', models.TextField(blank=True, null=True)),
                ('day_number', models.PositiveIntegerField(default=1, help_text="Jour de l'itinéraire")),
                ('duration_hours', models.FloatField(default=2.0, help_text='Durée estimée en heures')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities.city')),
                ('custom_itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='routes.customitinerary')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.hotel')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.place')),
            ],
            options={
                'verbose_name': "Étape d'itinéraire",
                'verbose_name_plural': "Étapes d'itinéraire",
                'ordering': ['custom_itinerary', 'day_number', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='routes.itinerary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('itinerary', 'user')},
            },
        ),
    ]
