# Generated by Django 5.2.10 on 2026-01-29 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0004_alter_touristplace_city'),
        ('hotels', '0007_alter_hotel_address_alter_hotel_price_and_more'),
        ('places', '0003_alter_place_options_remove_place_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False, help_text="Rendre l'itinéraire public")),
                ('views_count', models.PositiveIntegerField(default=0, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_itineraries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Itinéraire personnalisé',
                'verbose_name_plural': 'Itinéraires personnalisés',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Itinéraire sans nom', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('duration_days', models.IntegerField(default=1)),
                ('difficulty', models.CharField(choices=[('facile', 'Facile'), ('moyen', 'Moyen'), ('difficile', 'Difficile')], default='facile', max_length=20)),
                ('city', models.CharField(default='Marrakech', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='itineraries/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel_name', models.CharField(blank=True, max_length=200)),
                ('hotel_rating', models.IntegerField(default=0)),
                ('hotel_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hotel_address', models.CharField(blank=True, max_length=300)),
                ('stadium_name', models.CharField(blank=True, max_length=200)),
                ('stadium_address', models.CharField(blank=True, max_length=300)),
                ('distance', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('best_season', models.CharField(default="Toute l'année", max_length=100)),
                ('required_equipment', models.TextField(blank=True, default='Aucun équipement spécial requis')),
                ('contact_info', models.CharField(blank=True, default='Non disponible', max_length=200)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(blank=True, help_text='Hôtel de départ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='hotels.hotel')),
                ('stadium', models.ForeignKey(blank=True, help_text="Stade d'arrivée", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='places.stadium')),
            ],
            options={
                'verbose_name': 'Itinéraire',
                'verbose_name_plural': 'Itinéraires',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text="Ordre de l'étape")),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, help_text="Description de l'étape")),
                ('duration_hours', models.FloatField(blank=True, help_text='Durée estimée en heures', null=True)),
                ('is_optional', models.BooleanField(default=False, help_text='Étape facultative')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_stops', to='cities.city')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_stops', to='hotels.hotel')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='routes.customitinerary')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_stops', to='places.place')),
            ],
            options={
                'verbose_name': "Étape d'itinéraire",
                'verbose_name_plural': "Étapes d'itinéraire",
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('from_location', models.CharField(max_length=200)),
                ('to_location', models.CharField(max_length=200)),
                ('stadium_name', models.CharField(blank=True, max_length=200)),
                ('stadium_address', models.CharField(blank=True, max_length=300)),
                ('latitude_start', models.FloatField(default=0.0)),
                ('longitude_start', models.FloatField(default=0.0)),
                ('latitude_end', models.FloatField(default=0.0)),
                ('longitude_end', models.FloatField(default=0.0)),
                ('distance_km', models.FloatField(help_text='Distance en kilomètres')),
                ('estimated_time_min', models.IntegerField(help_text='Temps estimé en minutes')),
                ('transport_mode', models.CharField(choices=[('taxi', 'Taxi'), ('bus', 'Bus'), ('train', 'Train'), ('voiture', 'Voiture'), ('marche', 'À pied')], default='taxi', max_length=50)),
                ('price_estimate', models.DecimalField(decimal_places=2, help_text='Prix estimé du trajet', max_digits=10)),
                ('hotel', models.ForeignKey(help_text='Hôtel de départ', on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='hotels.hotel')),
                ('stadium', models.ForeignKey(blank=True, help_text="Stade d'arrivée", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='places.stadium')),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
                'ordering': ['hotel', 'stadium'],
            },
        ),
    ]
