# Generated by Django 5.2.10 on 2026-01-28 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='city',
            field=models.CharField(default='Marrakech', max_length=100),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='title',
            field=models.CharField(default='Itinéraire sans nom', max_length=200),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
