# Generated by Django 4.2.7 on 2026-01-30 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('routes', '0002_itinerary_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itinerarystop',
            options={'ordering': ['custom_itinerary', 'day_number', 'order'], 'verbose_name': "Étape d'itinéraire", 'verbose_name_plural': "Étapes d'itinéraire"},
        ),
        migrations.RenameField(
            model_name='itinerarystop',
            old_name='itinerary',
            new_name='custom_itinerary',
        ),
        migrations.AddField(
            model_name='customitinerary',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itinerary',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Public'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='itinerarystop',
            name='custom_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom personnalisé'),
        ),
        migrations.AddField(
            model_name='itinerarystop',
            name='day_number',
            field=models.PositiveIntegerField(default=1, help_text="Jour de l'itinéraire"),
        ),
        migrations.AddField(
            model_name='itinerarystop',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itinerarystop',
            name='duration_hours',
            field=models.FloatField(default=2.0, help_text='Durée estimée en heures'),
        ),
        migrations.AddField(
            model_name='itinerarystop',
            name='stop_type',
            field=models.CharField(choices=[('place', 'Lieu touristique'), ('hotel', 'Hôtel'), ('city', 'Ville'), ('other', 'Autre')], default='place', max_length=10),
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('share_method', models.CharField(blank=True, max_length=50, null=True)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='routes.itinerary')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='routes.itinerary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Like d'itinéraire",
                'verbose_name_plural': "Likes d'itinéraires",
                'unique_together': {('itinerary', 'user')},
            },
        ),
    ]
