# Generated by Django 6.0.1 on 2026-01-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_remove_hotel_image_url_remove_hotel_stars_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hotels/'),
        ),
    ]
