# Generated by Django 5.2.10 on 2026-01-28 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_add_hotels_data'),
    ]

    operations = [
    ]
