# Generated by Django 5.2.10 on 2026-01-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_add_hotels_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
