# Generated by Django 4.2.7 on 2026-01-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_alter_hotel_address_alter_hotel_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='address',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Prix par nuit (MAD)'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, help_text='Note sur 5 étoiles'),
        ),
    ]
