# Generated by Django 4.2.7 on 2026-01-14 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Description')),
                ('type', models.CharField(choices=[('monument', 'Monument'), ('museum', 'Musée'), ('park', 'Parc'), ('beach', 'Plage'), ('market', 'Marché'), ('religious', 'Site religieux'), ('other', 'Autre')], max_length=20, verbose_name='Type')),
                ('image', models.ImageField(blank=True, null=True, upload_to='places/', verbose_name='Image')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Adresse')),
                ('opening_hours', models.TextField(blank=True, verbose_name="Horaires d'ouverture")),
                ('price_range', models.CharField(blank=True, max_length=100, verbose_name='Fourchette de prix')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='cities.city')),
            ],
            options={
                'verbose_name': 'Lieu touristique',
                'verbose_name_plural': 'Lieux touristiques',
                'ordering': ['name'],
            },
        ),
    ]
