# Generated by Django 5.2.10 on 2026-01-25 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cities", "0003_add_initial_cities"),
    ]

    operations = [
        migrations.AlterField(
            model_name="touristplace",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tourist_places",
                to="cities.city",
            ),
        ),
    ]
