# Generated by Django 4.2.7 on 2026-01-14 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0002_touristplace'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_host', models.BooleanField(default=True, verbose_name='Ville hôte')),
                ('stadium_capacity', models.IntegerField(verbose_name='Capacité du stade')),
                ('matches_count', models.IntegerField(verbose_name='Nombre de matchs')),
                ('infrastructure_details', models.TextField(blank=True, verbose_name='Infrastructures')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worldcup_host', to='cities.city')),
            ],
            options={
                'verbose_name': 'Ville hôte',
                'verbose_name_plural': 'Villes hôtes',
                'ordering': ['city__name'],
            },
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du stade')),
                ('capacity', models.IntegerField(verbose_name='Capacité')),
                ('construction_year', models.IntegerField(verbose_name='Année de construction')),
                ('image', models.ImageField(blank=True, null=True, upload_to='stadiums/', verbose_name='Image')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Adresse')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stadiums', to='worldcup2030.hostcity')),
            ],
            options={
                'verbose_name': 'Stade',
                'verbose_name_plural': 'Stades',
                'ordering': ['name'],
            },
        ),
    ]
